=== ekapratamap/Tugas-Webservice-2-/industrijasa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="logindustrijasa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Gojek"/>
                <xs:element ref="Grab"/>
                <xs:element ref="Laundry"/>
                <xs:element ref="Taksi"/>
                <xs:element ref="Uber"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Gojek">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="driver"/>
                <xs:element ref="alamat"/>
                <xs:element ref="jk"/>
                <xs:element ref="trfhrg"/>
                <xs:element ref="agama"/>
                <xs:element ref="pekerjaan"/>
                <xs:element ref="nohp"/>
                <xs:element ref="asal"/>
                <xs:element ref="tujuan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Grab">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="driver"/>
                <xs:element ref="alamat"/>
                <xs:element ref="jk"/>
                <xs:element ref="trfhrg"/>
                <xs:element ref="agama"/>
                <xs:element ref="pekerjaan"/>
                <xs:element ref="nohp"/>
                <xs:element ref="asal"/>
                <xs:element ref="tujuan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Laundry">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="nama"/>
                <xs:element ref="pemilik"/>
                <xs:element ref="alamat"/>
                <xs:element ref="nohp"/>
                <xs:element ref="hrg"/>
                <xs:element ref="email"/>
                <xs:element ref="no"/>
                <xs:element ref="tahunbuka"/>
                <xs:element ref="kurir"/>
                <xs:element ref="harikrj"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nama" type="xs:string"/>
    <xs:element name="pemilik" type="xs:NCName"/>
    <xs:element name="hrg" type="xs:string"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="no" type="xs:string"/>
    <xs:element name="tahunbuka" type="xs:integer"/>
    <xs:element name="kurir" type="xs:NCName"/>
    <xs:element name="harikrj" type="xs:NCName"/>
    <xs:element name="Taksi">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="driver"/>
                <xs:element ref="alamat"/>
                <xs:element ref="jk"/>
                <xs:element ref="trfhrg"/>
                <xs:element ref="agama"/>
                <xs:element ref="pekerjaan"/>
                <xs:element ref="nohp"/>
                <xs:element ref="asal"/>
                <xs:element ref="tujuan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Uber">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="driver"/>
                <xs:element ref="alamat"/>
                <xs:element ref="jk"/>
                <xs:element ref="trfhrg"/>
                <xs:element ref="agama"/>
                <xs:element ref="pekerjaan"/>
                <xs:element ref="nohp"/>
                <xs:element ref="asal"/>
                <xs:element ref="tujuan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="kode">
    	<xs:simpleType>
    		<xs:restriction base="xs:NCName">
    			<xs:minLength value="5"></xs:minLength>
    			<xs:maxLength value="10"></xs:maxLength>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="driver" type="xs:NCName"/>
    <xs:element name="alamat" type="xs:NCName"/>
    <xs:element name="jk" type="xs:NCName"/>
    <xs:element name="trfhrg" type="xs:integer"/>
    <xs:element name="agama" type="xs:NCName"/>
    <xs:element name="pekerjaan" type="xs:NCName"/>
    <xs:element name="nohp" type="xs:integer"/>
    <xs:element name="asal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pt"/>
                <xs:element ref="kodewil"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pt" type="xs:string"/>
    <xs:element name="kodewil" type="xs:integer"/>
    <xs:element name="tujuan" type="xs:string"/>
</xs:schema>

=== ekapratamap/Tugas-Webservice-2-/industrijasa.xml
<?xml version="1.0" encoding="UTF-8"?>
<logindustrijasa xsi:noNamespaceSchemaLocation="industrijasa.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Gojek>
<kode>M12341</kode>
		<driver>Nanang</driver>
		<alamat>bandung</alamat>
		<jk>Laki-laki</jk>
		<trfhrg>15000</trfhrg>
		<agama>islam</agama>
		<pekerjaan>driver</pekerjaan>
		<nohp>085237384625</nohp>
		<asal>
			<pt>gojek indonesia</pt>
			<kodewil>465</kodewil>
		</asal>
	<tujuan>Wilayah Bandung</tujuan>
</Gojek>
<Grab>
<kode>G2347</kode>
		<driver>Kevin</driver>
		<alamat>bandung</alamat>
		<jk>Laki-laki</jk>
		<trfhrg>20000</trfhrg>
		<agama>islam</agama>
		<pekerjaan>driver</pekerjaan>
		<nohp>085242425365</nohp>
		<asal>
			<pt>grab indonesia</pt>
			<kodewil>089</kodewil>
		</asal>
	<tujuan>Wilayah Bandung</tujuan>
</Grab>
<Laundry>
<kode>L7346</kode>
		<nama>Napuri Laundry</nama>
		<pemilik>Sulmiati</pemilik>
		<alamat>bandung</alamat>
		<nohp>085283567125</nohp>
		<hrg>7000/kg</hrg>
		<email>napurilaundry@gmail.com</email>
		<no>Kode Baju Pelanggan</no>
		<tahunbuka>2014</tahunbuka>
		<kurir>Bayu</kurir>
		<harikrj>Senin-Sabtu</harikrj>
</Laundry>
<Taksi>
<kode>T3689</kode>
		<driver>Kurniawan</driver>
		<alamat>bandung</alamat>
		<jk>Laki-laki</jk>
		<trfhrg>20000</trfhrg>
		<agama>islam</agama>
		<pekerjaan>driver</pekerjaan>
		<nohp>085534576345</nohp>
		<asal>
			<pt>taksi indonesia</pt>
			<kodewil>905</kodewil>
		</asal>
		<tujuan>Wilayah Bandung</tujuan>
</Taksi>
<Uber>
<kode>U9865</kode>
		<driver>Sanjaya</driver>
		<alamat>bandung</alamat>
		<jk>Laki-laki</jk>
		<trfhrg>20000</trfhrg>
		<agama>islam</agama>
		<pekerjaan>driver</pekerjaan>
		<nohp>085567890456</nohp>
		<asal>
			<pt>uber indonesia</pt>
			<kodewil>231</kodewil>

		</asal>
		<tujuan>Wilayah Bandung</tujuan>
</Uber>
</logindustrijasa>
